version: '3.8'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge